# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4f4cb467f0342a8adf97a1267134c666410c6b53dea3d5ba77940031ca60b5ece935e5c65903eae64958a81e70d292e13f510b62c75d3e8f7e24b9780acb7ed

test:
  secret_key_base: b77cf56c62df2a05fe8adab92b1bdd221dfa6f49f8ff17254aaf5b8913cc60130a1db73d002860be7d94f352824b66cc8ca285605c7cffa0dd1b14c5584103e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
